### ISSUE TITLE
PendingIntent flag error on android 12

### ISSUE THREAD

**Issue by jerry0513** [algolia/instantsearch-android#271]
**Describe the bug 🐛**
  I set compileSdk and targetSdk to 31,
  get the PendingIntent flag error when launch app on android 12 emulator

**To Reproduce 🔍**
  build.gradle :
    compileSdk 31
    targetSdk 31

**Expected behavior 💭**
  no error

**Screenshots 🖥**
![error](https://user-images.githubusercontent.com/32190495/143467704-1873a79a-10bd-4644-90ce-e2d0218ec0a0.PNG)

**Environment:**
 - OS: android studio android 12 emulator 
 - Library Version: 2.11.1

**Comment by Aallam** [comment]
Hi @jerry0513 - is this error from the [showcase](https://github.com/algolia/instantsearch-android-examples) repository?

**Comment by jerry0513** [comment]
@Aallam my project is also get the error

**Comment by Aallam** [comment]
Hello @jerry0513 -- the issue is related to android's [workmanager](https://issuetracker.google.com/issues/196033705); you can fix it by either:
- Update the libary to version [`2.11.2`](https://github.com/algolia/instantsearch-android/releases/tag/2.11.2), which updates it dependencies.
- Or, depend on version `2.7.0` or above of [workmanager](https://developer.android.com/jetpack/androidx/releases/work#2.7.0): `implementation 'androidx.work:work-runtime:2.7.0'`
