### ISSUE TITLE
HttpClient: RESPONSE https://xxxx-dsn.algolia.net/1/indexes/*/queries failed with exception: kotlinx.serialization.MissingFieldException

### ISSUE THREAD

**Issue by lucamtudor** [algolia/instantsearch-android#294]
**Describe the bug 🐛**

I'm following the Declarative UI guide & the Compose examples from this repo with lib version 3.0.0-beta01. I've set LogLevel.ALL. 

Even though I can see my queries & responses in Logcat, the UI shows nothing. I keep seeing this line in Logcat:

> HttpClient: RESPONSE https://xxxx-dsn.algolia.net/1/indexes/*/queries failed with exception: kotlinx.serialization.MissingFieldException: Field 'values' is required for type with serial name 'com.algolia.search.model.rule.FacetOrdering', but it was missing

If I switch my code to use the algolia app & index from the examples repo, it works.

**Environment:**
 - OS: macOS, android
 - Library Version 3.0.0-beta01

**Comment by Aallam** [comment]
Hi @lucamtudor, thanks for sharing this. 

The issue is related to the [Kotlin API client](https://github.com/algolia/algoliasearch-client-kotlin/pull/323), and has been fixed.

The Kotlin API client version will be updated in the next iteration, meanwhile, in your Gradle dependencies add the following to depend on the latest version: `implementation com.algolia:algoliasearch-client-kotlin:1.13.0`
