### ISSUE TITLE
Cannot find the setter for attribute 'algolia:attribute' with parameter type java.lang.String on android.widget.ImageView.

### ISSUE THREAD

**Issue by trogalko** [algolia/instantsearch-android#72]
I know this this issue has been solved in the previous version of Algolia instantsearch, I can run this example  without error. But when I tried to combine this example (add this to google firestore fireeats example project), this error reappear. First it happen on TextView, but i solved it by creating custom view with no error. After I updated fireeats dependencies to the latest version (due to email auth error), I have similar error on ImageView. Can I create custom ImageView or maybe there is information about conflicted (version of) dependencies between Firestore fireeats example project with Algolia instantsearch example project?
Thank You,

**Comment by PLNech** [comment]
Hi @trogalko, thanks for reporting this!

I understand the frustration, this error message is super misleading. Basically it appears when there is a mismatch between a databinding expression and its `BindingAdapter`, like so:
```xml
<TextView
    android:id="@+id/product_manufacturer"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    algolia:attribute='@{"manufacturer"}'
    algolia:highlighted='@{"true"}' />
```
```java
@BindingAdapter(value = {"attribute", "highlighted")
    public static void bindAttribute(@NonNull View view, @Nullable String attribute,
                                     @Nullable Boolean highlighted) {
    // Adapter code
}
```
Note that the String `attribute` is _correctly bound_, but the view *misuses `highlighted`* by giving a `String` instead of a `Boolean`. 
This results in the same error message as you, misleading you in believing the issue is the first expression: 
```
****/ data binding error ****
msg:Cannot find the setter for attribute 'algolia:attribute' with parameter type java.lang.String on com.algolia.instantsearch.examples.querysuggestions.NotNullTextView. ****\ data binding error ****
```

----

With that in mind, check your databinding expressions and compare them to the expected types in the BindingAdapter. The issue likely comes from here, if not feel free to reopen this ticket and show me your bindings code so we can investigate further !
 
_As you noticed you can choose not to use the databinding system by creating custom views, but this is not needed provided you use the data binding expressions with the right types :)_

**Comment by trogalko** [comment]
Thank You so much,
First I want to apologize because I posted issue to the wrong project, it should be here [https://github.com/algolia/instantsearch-android-examples](url)
Look like the problem is in Android Studio,
When I remove the ImageView widget, it still show the same error, so I suspect the error is in the cache.
I deleted all content on .Gradle and .idea folder  , followed by gradle resync and rebuild all, then all errors are gone.

**Comment by PLNech** [comment]
Hi @trogalko, thanks for the follow-up. I second your suspicion, as I too had issues with databinding that were cleared by resetting `.idea`. 

For future readers of this issue, if you have the same error message but have no error in your databinding expressions, this is the the likely culprit!
